name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Deno 2.4.1
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.4.1

      - name: Run deno fmt --check
        run: deno fmt --check

      - name: Run deno lint
        run: deno lint

      - name: Run deno test
        run: deno test --allow-all

      - name: Publish to JSR
        run: npx jsr publish
