# .github/workflows/publish.yml

name: Test and Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  
    steps:
      - uses: actions/checkout@v3

      - name: Use Deno 2.4.1
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.4.1

      - run: deno fmt --check
      - run: deno lint
      - run: deno test
      - uses: actions/checkout@v4
      - run: npx jsr publish